FROM xrsec/osinit:centos
LABEL maintainer="xrsec"
LABEL mail="troy@zygd.site"
LABEL Github="https://github.com/XRSec/Oracle_Java_Docker"
LABEL org.opencontainers.image.source="https://github.com/XRSec/Oracle_Java_Docker"
LABEL org.opencontainers.image.title="Oracle_Java_Docker"

ARG TARGETPLATFORM

COPY ${TARGETPLATFORM}/jdk-17_linux* /tmp/

RUN cat /tmp/jdk-17_linux* > /tmp/jdk17.rpm \
    && rpm -ivh /tmp/jdk17.rpm \
    && rm /tmp/jdk17.rpm

# ENV TZ='Asia/Shanghai'
# ENV LANG 'zh_CN.UTF-8'

# STOPSIGNAL SIGQUIT

CMD [ "/bin/bash"]
