FROM centos:latest
LABEL maintainer="xrsec"
LABEL mail="troy@zygd.site"
ARG TARGETPLATFORM

COPY ${TARGETPLATFORM}/jdk-8u301-linux* /tmp/

RUN cat /tmp/jdk-8u301-linux* > /tmp/jdk8.rpm \
    && rpm -ivh /tmp/jdk8.rpm \
    && rm /tmp/jdk8.rpm

# ENV TZ='Asia/Shanghai'
# ENV LANG 'zh_CN.UTF-8'

# STOPSIGNAL SIGQUIT

CMD [ "/bin/bash"]
