FROM centos:latest
LABEL maintainer="xrsec"
LABEL mail="troy@zygd.site"
ARG TARGETPLATFORM

COPY ${TARGETPLATFORM}/jdk-11.0.12_linux* /tmp/

RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* \
    && sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS -* \
    && yum clean all && yum makecache && yum update -y && yum upgrade -y

RUN cat /tmp/jdk-11.0.12_linux* > /tmp/jdk11.rpm \
    && rpm -ivh /tmp/jdk11.rpm \
    && rm /tmp/jdk11.rpm

# ENV TZ='Asia/Shanghai'
# ENV LANG 'zh_CN.UTF-8'

# STOPSIGNAL SIGQUIT

CMD [ "/bin/bash"]
