FROM xrsec/osinit:centos
LABEL maintainer="xrsec"
LABEL mail="Jalapeno1868@outlook.com"
LABEL Github="https://github.com/XRSec/Oracle_Java_Docker"
LABEL org.opencontainers.image.source="https://github.com/XRSec/Oracle_Java_Docker"
LABEL org.opencontainers.image.title="Oracle_Java_Docker"

ARG TARGETPLATFORM

COPY ${TARGETPLATFORM}/jdk-16.0.2_linux* /tmp/

RUN cat /tmp/jdk-16.0.2_linux* > /tmp/jdk16.rpm \
    && rpm -ivh /tmp/jdk16.rpm \
    && rm /tmp/jdk16.rpm

# ENV TZ='Asia/Shanghai'
# ENV LANG 'zh_CN.UTF-8'

# STOPSIGNAL SIGQUIT

CMD [ "/bin/bash"]
